# Generated by Django 4.2.14 on 2024-08-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0003_evento_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='descricao',
            field=models.TextField(blank=True, help_text='Coque aqui uma descrição do evento para ajudar os autores a submeterem seus trabalhos', max_length=200, null=True, verbose_name='Descrição do evento'),
        ),
    ]
