# Generated by Django 4.2.14 on 2024-08-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissao', '0004_alter_submissao_abstract_alter_submissao_observacoes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissao',
            name='abstract',
            field=models.TextField(help_text='Se for colar texto de outro aplicativo, certifique-se que o abstract esteja completo', max_length=1000, verbose_name='Abstract *'),
        ),
        migrations.AlterField(
            model_name='submissao',
            name='observacoes',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Caso necessite, área para registro de justificativas e/ou apontamentos para o responsável da submissão'),
        ),
        migrations.AlterField(
            model_name='submissao',
            name='resumo',
            field=models.TextField(help_text='Se for colar texto de outro aplicativo, certifique-se que o resumo esteja completo', max_length=1000, verbose_name='Resumo *'),
        ),
    ]
