# Generated by Django 4.2.14 on 2024-07-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_usuario_aceita_termo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='aceita_termo',
            field=models.BooleanField(default=False, help_text='Se marcado, usuário tem consentimento de uso do sistema', verbose_name='Marque o aceite do termo de consentimento'),
        ),
    ]
